# -*- coding: utf-8 -*-
{
    "name": "seta_lookup",
    "summary": """Container for SETMIS Lookups""",
    "description": """Container for SETMIS and (Other) Lookups""",
    "author": "HWSETA",
    "website": "http://www.hwseta.org.za",
    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/15.0/odoo/addons/base/data/ir_module_category_data.xml
    # for the full list
    "category": "seta",
    "version": "0.1",
    # any module necessary for this one to work correctly
    "depends": ["base"],
    # always loaded
    "data": [
        "security/security_categories.xml",
        "security/security_groups.xml",
        "security/ir.model.access.csv",
        "data/disability.xml",
        "data/abet_band.xml",
        "data/aet_level.xml",
        "data/alternate_id_type_id.xml",
        "data/citizen_resident_status_code.xml",
        "data/city_code.xml",
        "data/communicating_rating_id.xml",
        "data/country_code.xml",
        "data/designation_id.xml",
        "data/designation_structure_status_id.xml",
        "data/disability_code.xml",
        "data/district.xml",
        "data/economic_status_id.xml",
        "data/employer_approval_status_id.xml",
        "data/enrolment_status_id.xml",
        "data/enrolment_status_reason_id.xml",
        "data/enrolment_type_id.xml",
        "data/equity_code.xml",
        "data/etqe_id.xml",
        "data/financial_year_code.xml",
        "data/funding_id.xml",
        "data/gender_code.xml",
        "data/h_f_rating.xml",
        "data/hearing_rating_id.xml",
        "data/highest_education.xml",
        "data/home_language_code.xml",
        "data/honours_classification_id.xml",
        #"data/identification_type.xml",
        "data/internship_status_id.xml",
        "data/last_school_year.xml",
        "data/learner_achievement_status_id.xml",
        "data/learner_achievement_type_id.xml",
        "data/learnership_nqf.xml",
        "data/learnership_pre_nqf.xml",
        "data/learnership_status.xml",
        "data/learning_programme_type_id.xml",
        "data/marital_status_id.xml",
        "data/municipality.xml",
        "data/nationality_code.xml",
        "data/non_nqf_interv_status_id.xml",
        "data/nqf_design_status_code.xml",
        "data/nqf_level.xml",
        #"data/ofo_extended.xml",
        # "data/ofo_2021.xml",
        # "data/ofo_code.xml",
        "data/ofo_code_new.xml",
        # "data/ofo.xml",
        "data/part_of_id.xml",
        "data/popi_act_status_id.xml",
        "data/provider_accred_status_code.xml",
        "data/provider_accredit_assessor_ind.xml",
        "data/provider_class_id.xml",
        "data/provider_status_id.xml",
        "data/provider_type_id.xml",
        "data/province_code.xml",
        "data/qualification_type_id.xml",
        "data/remembering_rating_id.xml",
        "data/scheme_year_code.xml",
        "data/seeing_rating_id.xml",
        "data/self_care_rating_id.xml",
        "data/seta_id.xml",
        "data/sic_code.xml",
        "data/socioeconomic_status_code.xml",
        "data/statssa_area_code.xml",
        "data/subfield_id.xml",
        "data/trade_test_result_id.xml",
        "data/trade_test_result_reason_id.xml",
        "data/training_type.xml",
        "data/urban_rural_id.xml",
        "data/walking_rating_id.xml",
        "data/type_of_training_intervention.xml",
        "data/suburb.xml",
        "views/menu_item.xml",
        "views/abet_band.xml",
        "views/aet_level.xml",
        "views/alternate_id_type_id.xml",
        "views/citizen_resident_status_code.xml",
        "views/city_code.xml",
        "views/communicating_rating_id.xml",
        "views/country_code.xml",
        "views/designation_id.xml",
        "views/designation_structure_status_id.xml",
        "views/disability_code.xml",
        "views/district.xml",
        "views/economic_status_id.xml",
        "views/employer_approval_status_id.xml",
        "views/enrolment_status_id.xml",
        "views/enrolment_status_reason_id.xml",
        "views/enrolment_type_id.xml",
        "views/equity_code.xml",
        "views/etqe_id.xml",
        "views/financial_year_code.xml",
        "views/funding_id.xml",
        "views/gender_code.xml",
        "views/h_f_rating.xml",
        "views/hearing_rating_id.xml",
        "views/highest_education.xml",
        "views/home_language_code.xml",
        "views/honours_classification_id.xml",
        #"views/identification_type.xml",
        "views/internship_status_id.xml",
        "views/last_school_year.xml",
        "views/learner_achievement_status_id.xml",
        "views/learner_achievement_type_id.xml",
        "views/learnership_nqf.xml",
        "views/learnership_pre_nqf.xml",
        "views/learnership_status.xml",
        "views/learning_programme_type_id.xml",
        "views/marital_status_id.xml",
        "views/municipality.xml",
        "views/nationality_code.xml",
        "views/non_nqf_interv_status_id.xml",
        "views/nqf_design_status_code.xml",
        "views/nqf_level.xml",
        "views/ofo.xml",
        "views/ofo_code.xml",
        "views/part_of_id.xml",
        "views/popi_act_status_id.xml",
        "views/provider_accred_status_code.xml",
        "views/provider_accredit_assessor_ind.xml",
        "views/provider_class_id.xml",
        "views/provider_status_id.xml",
        "views/provider_type_id.xml",
        "views/province_code.xml",
        "views/qualification_type_id.xml",
        "views/remembering_rating_id.xml",
        "views/scheme_year_code.xml",
        "views/seeing_rating_id.xml",
        "views/self_care_rating_id.xml",
        "views/seta_id.xml",
        "views/sic_code.xml",
        "views/socioeconomic_status_code.xml",
        "views/statssa_area_code.xml",
        "views/subfield_id.xml",
        "views/trade_test_result_id.xml",
        "views/trade_test_result_reason_id.xml",
        "views/training_type.xml",
        "views/urban_rural_id.xml",
        "views/walking_rating_id.xml",
        "views/suburb.xml",
        "views/ofo_code_new.xml",
    ],
    # only loaded in demonstration mode
    "demo": [
        "demo/lookup_demo_data.xml",
    ],
}
