from . import type_of_training_intervention
from . import disability
from . import designation_id
from . import nqf_level
from . import aet_level
from . import training_type
from . import pivotal_programme_qualification
from . import identification_type
from . import highest_education
from . import disability_code
from . import designation_structure_status_id
from . import seta_id
from . import sic_code
from . import internship_status_id
from . import enrolment_status_id
from . import enrolment_status_reason_id
from . import trade_test_result_reason_id
from . import trade_test_result_id
from . import economic_status_id
from . import employer_approval_status_id
from . import province_code
from . import city_code
from . import funding_id
from . import etqe_id
from . import urban_rural_id
from . import non_nqf_interv_status_id
from . import subfield_id
from . import alternate_id_type_id
from . import equity_code
from . import nationality_code
from . import home_language_code
from . import gender_code
from . import citizen_resident_status_code
from . import seeing_rating_id
from . import hearing_rating_id
from . import walking_rating_id
from . import remembering_rating_id
from . import communicating_rating_id
from . import self_care_rating_id
from . import statssa_area_code
from . import popi_act_status_id
from . import provider_type_id
from . import provider_class_id
from . import provider_status_id
from . import enrolment_type_id
from . import part_of_id
from . import district
from . import municipality
from . import suburb
from . import last_school_year
from . import financial_year_code
from . import scheme_year_code
from . import marital_status_id
from . import learning_programme_type_id
from . import qualification_type_id
from . import ofo_code
from . import ofo
from . import ofo_new
from . import country_code
from . import honours_classification_id
from . import provider_accredit_assessor_ind
from . import provider_accred_status_code
from . import nqf_design_status_code
from . import h_f_rating
from . import menu_sequence
from . import city_code
from . import create_record_mixin
from . import learnership_nqf
from . import learnership_pre_nqf
from . import learnership_status
from . import learner_achievement_status_id
from . import learner_achievement_type_id
from . import socioeconomic_status_code
from . import abet_band
